name: Deploy to Github Pages on merge
'on':
  push:
    branches:
      - staging
jobs:

  build_and_deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          npm ci && npm run build -- --prod --base-href "https://tsunilrao.github.io/mat-ex/"
          cp dist/mat-ex-app/index.html dist/mat-ex-app/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/mat-ex-app
          